tap "buo/cask-upgrade"
tap "charmbracelet/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "puppetlabs/puppet"
tap "vitorgalvao/tiny-scripts"
tap "yt-dlp/taps"
# Run your GitHub Actions locally
brew "act"
# Generic-purpose lossless compression algorithm by Google
brew "brotli"
# Library and utilities for processing GIFs
brew "giflib"
# Library of 2D and 3D vector, matrix, and math operations
brew "imath"
# Library for manipulating PNG images
brew "libpng"
# Extremely Fast Compression algorithm
brew "lz4"
# General-purpose data compression with high compression ratio
brew "xz"
# Zstandard is a real-time compression algorithm
brew "zstd"
# TIFF library and utilities
brew "libtiff"
# Color management engine supporting ICC profiles
brew "little-cms2"
# High dynamic-range image file format
brew "openexr"
# Image format providing lossless and lossy compression for web images
brew "webp"
# Perceptual video quality assessment based on multi-method fusion
brew "libvmaf"
# Apache Portable Runtime library
brew "apr"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Companion library to apr, the Apache Portable Runtime library
brew "apr-util"
# Library for command-line editing
brew "readline"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Text processor and publishing toolchain for AsciiDoc
brew "asciidoctor"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Spell checker with better logic than ispell
brew "aspell"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 3.2
brew "bash-completion"
# Regular expressions library
brew "oniguruma"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Garbage collector for C and C++
brew "bdw-gc"
# Fish completion for brew-cask
brew "brew-cask-completion"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Software library to render fonts
brew "freetype"
# XML-based font configuration API for X Windows
brew "fontconfig"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Perl compatible regular expressions library with a new API
brew "pcre2"
# Core application library for C
brew "glib"
# X.Org: Protocol Headers
brew "xorgproto"
# X.Org: A Sample Authorization Protocol for X
brew "libxau"
# X.Org: X Display Manager Control Protocol library
brew "libxdmcp"
# X.Org: Interface to the X Window System protocol
brew "libxcb"
# X.Org: Core X11 protocol client library
brew "libx11"
# X.Org: Library for common extensions to the X11 protocol
brew "libxext"
# X.Org: Library for the Render Extension to the X11 protocol
brew "libxrender"
# Real-time data compression library
brew "lzo"
# Low-level library for pixel manipulation
brew "pixman"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Human-friendly and fast alternative to cut and (sometimes) awk
brew "choose-rust"
# Cross-platform make
brew "cmake"
# Reimplementation of ctags(1)
brew "ctags"
# AV1 decoder targeted to be small and fast
brew "dav1d"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Standard SGML representation system for technical documents
brew "docbook"
# XML vocabulary to create presentation-neutral documents
brew "docbook-xsl"
# Convert text between DOS, UNIX, and Mac formats
brew "dos2unix"
# Disk Usage/Free Utility - a better 'df' alternative
brew "duf"
# Quickly find duplicates in a set of files from the command-line
brew "duff"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Modern, maintained replacement for ls
brew "eza"
# Identify or delete duplicate files
brew "fdupes"
# Minimalistic plugin API for video effects
brew "frei0r"
# Implementation of the Unicode BiDi algorithm
brew "fribidi"
# Asynchronous event library
brew "libevent"
# C string library for manipulating Unicode strings
brew "libunistring"
# International domain name library (IDNA2008, Punycode and TR46)
brew "libidn2"
# HTTP/2 C Library
brew "libnghttp2"
# ASN.1 structure parser library
brew "libtasn1"
# Low-level cryptographic library
brew "nettle"
# Library to load and enumerate PKCS#11 modules
brew "p11-kit"
# Validating, recursive, caching DNS resolver
brew "unbound"
# Smart font renderer for non-Roman scripts
brew "graphite2"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c"
# OpenType text shaping engine
brew "harfbuzz"
# Library for JPEG-2000 image manipulation
brew "openjpeg"
# Framework for layout and rendering of i18n text
brew "pango"
# H.265/HEVC encoder
brew "x265"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Terminal JSON viewer
brew "fx"
# JBIG2 decoder and library (for monochrome documents)
brew "jbig2dec"
# International domain name library
brew "libidn"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Distributed revision control system
brew "git"
# Git extension for versioning large files
brew "git-lfs"
# Render markdown on the CLI
brew "glow"
# Command-line option parsing utility
brew "gnu-getopt"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Ping, but with a graph
brew "gping"
# Make JSON greppable
brew "gron"
# Library for manipulating JPEG-2000 images
brew "jasper"
# Image manipulation
brew "netpbm"
# GNU triangulated surface library
brew "gts"
# Manage compile and link flags for libraries
brew "pkg-config"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# Post-modern modal text editor
brew "helix"
# Command-line hex viewer
brew "hexyl"
# <hr />, for your terminal window
brew "hr"
# Text-based UI library
brew "ncurses"
# Improved top (interactive process viewer)
brew "htop"
# Curl statistics made simple
brew "httpstat"
# Add GitHub support to git on the command-line
brew "hub"
# Display an interface's bandwidth usage
brew "iftop"
# Open h.265 video codec implementation
brew "libde265"
# Database of common MIME types
brew "shared-mime-info"
# LLVM's OpenMP runtime library
brew "libomp", link: true
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Modular IRC client
brew "irssi"
# C library for encoding, decoding, and manipulating JSON
brew "jansson"
# Serializes the output of command-line tools to structured JSON output
brew "jc"
# Image manipulation library
brew "jpeg"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Portable Foreign Function Interface library
brew "libffi"
# X.Org: pthread-stubs.pc
brew "libpthread-stubs"
# Library to render SVG files using Cairo
brew "librsvg"
# Lynx-like WWW browser that supports tables, menus, etc.
brew "links"
# Next-gen compiler infrastructure
brew "llvm"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Python 2 and 3 compatibility utilities
brew "six"
# Mac App Store command-line interface
brew "mas"
# Fast and user friendly build system
brew "meson"
# Run a Kubernetes cluster locally
brew "minikube"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Remote terminal application
brew "mosh"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# Netwide Assembler (NASM) is an 80x86 assembler
brew "nasm"
# NCurses Disk Usage
brew "ncdu"
# Get, set, and list display resolution
brew "screenresolution"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# No Nonsense Neovim Client in Rust
brew "neovide"
# Net top tool grouping bandwidth per process
brew "nethogs"
# Perl compatible regular expressions library
brew "pcre"
# Port scanning utility for large networks
brew "nmap"
# Development kit for the Java programming language
brew "openjdk"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Simplistic interactive filtering tool
brew "peco"
# Parallel gzip
brew "pigz"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Rename your files using your favorite text editor
brew "pipe-rename"
# Optimizer for PNG files
brew "pngcrush"
# Monitor data's progress through a pipe
brew "pv"
# Password generator
brew "pwgen"
# Generic machine emulator and virtualizer
brew "qemu"
# Install various Ruby versions and implementations
brew "ruby-build"
# Ruby version manager
brew "rbenv"
# Web Reconnaissance Framework
brew "recon-ng"
# Perl-powered file rename script with many helpful built-ins
brew "rename"
# Fast, efficient and secure backup program
brew "restic"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Prevent committing secret keys into your source code
brew "ripsecrets"
# Safe, concurrent, practical language
brew "rust"
# Intuitive find & replace CLI
brew "sd"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Count lines of code in many languages
brew "sloccount"
# Yet another network load monitor
brew "slurm"
# Semi-automatic OSINT framework and package manager
brew "sn0int"
# Daemon to provide vmnet.framework support for rootless QEMU
brew "socket_vmnet"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Add a public key to a remote machine's authorized_keys file
brew "ssh-copy-id"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Clean C library for processing UTF-8 Unicode data
brew "utf8proc"
# Version control system designed to be a better CVS
brew "subversion"
# Tool Command Language
brew "tcl-tk"
# User interface to the TELNET protocol
brew "telnet"
# Code-search similar to ack
brew "the_silver_searcher"
# TIFF to PNG converter
brew "tiff2png"
# Text interface for Git repositories
brew "tig"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Source code spell checker
brew "typos-cli"
# Data compression library with small memory footprint
brew "ucl"
# Tool for writing command-line pipes with instant live preview
brew "up"
# Compress/expand executable files
brew "upx"
# X.Org: Set of autoconf macros used to build other xorg packages
brew "util-macros"
# Google's JavaScript engine
brew "v8"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# Userspace Go implementation of WireGuard
brew "wireguard-go"
# Tools for the WireGuard secure network tunnel
brew "wireguard-tools"
# Convert XML to another format (based on XSL or other tools)
brew "xmlto"
# Fast CSV toolkit written in Rust
brew "xsv"
# X.Org: X Network Transport layer shared code
brew "xtrans"
# Bring your favorite shell wherever you go through the ssh
brew "xxh"
# Fork of youtube-dl with additional features and fixes
brew "yt-dlp"
# The Charm Tool and Library 🌟
brew "charmbracelet/tap/charm"
# A tool for glamorous shell scripts
brew "charmbracelet/tap/gum"
# Quickly repair outdated/broken Casks from homebrew-cask
brew "vitorgalvao/tiny-scripts/cask-repair"
# Web browser
cask "firefox"
# Developer targeted fonts with a high number of glyphs
cask "font-fira-mono-nerd-font"
# PDF reader
cask "foxitreader"
# Full TeX Live distribution with GUI applications
cask "mactex"
# Store SSH keys in the Secure Enclave
cask "secretive"
# System monitor for the menu bar
cask "stats"
# Customizable email client
cask "thunderbird"
# Video communication and virtual meeting platform
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Apple Configurator", id: 1037126344
mas "Deliveries", id: 290986013
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Mactracker", id: 430255202
mas "MoneyMoney", id: 872698314
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pomo Timer", id: 1447569061
mas "Reeder", id: 1529448980
mas "Sweet Home 3D", id: 669289700
mas "Telephone", id: 406825478
mas "Texifier", id: 458866234
mas "Things", id: 904280696
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
